### ISSUE TITLE
River

### ISSUE THREAD

**Issue by bnjmnt4n** [bnjmnt4n/system#14]
https://github.com/ifreund/river

**Comment by branwright1** [comment]
River is already in nixpkgs-master and wjll be merged into unstable in few days, so you don't need to bother with making own derivation.

**Comment by bnjmnt4n** [comment]
Yeap, thanks for the heads-up! I was also planning on waiting till damage tracking has been implemented before adding this to my laptop.

**Comment by bnjmnt4n** [comment]
Closing since I'm not going to use a Linux system for the foreseeable future.
